# 딥 슬립 활성화 (배터리 절약 필수 옵션)
CONFIG_ZMK_SLEEP=y
# 15분(900,000ms) 동안 입력 없으면 딥 슬립 진입
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 블루투스 신호 출력 정상화 (배터리 광탈 방지)
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 초고속 디바운스 설정 (속타용)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# ZMK Studio 실시간 키맵 변경 활성화
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 마우스 키 마우스 포인팅 기능 활성화
CONFIG_ZMK_POINTING=y

# [배터리 센터용] 반대쪽 배터리 레벨 메인으로 가져오기
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# [배터리 센터용] 가져온 배터리 레벨 컴퓨터/안드로이드로 토스하기
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
